apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: habitforge-ingress
  namespace: habitforge
  labels:
    app: habitforge
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rate-limit-connections: "10"
    nginx.ingress.kubernetes.io/rate-limit-rps: "20"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.habitforge.dev
      secretName: habitforge-tls
  rules:
    - host: api.habitforge.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: habitforge-service
                port:
                  number: 80
